{% set version = "5.5.985" %}
{% set commit = "94f3762603ba31e39b8ebf618cf0608fa5f1338f" %}

package:
  name: kaldi
  version: {{ version }}

source:
  fn: {{ version }}-{{ commit }}.tar.gz
  url: https://github.com/kaldi-asr/kaldi/archive/{{ commit }}.tar.gz
  sha256: 6235b76b4142e99afab5115472c7f77ebd65b9f01a5427ed57fa34ec63a77810
  patches:
    - cmake.patch

build:
  number: 1
    
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - m2-patch  # [win]
    - ninja
    - libtool  # [not win]
    - automake  # [not win]
  host:
    - openblas
    - pthreads-win32  # [win]
    - wget  # [not win]
    - sox  # [not win]
    - zlib  # [not win]
    - subversion  # [not win]
    - gfortran  # [not win]
    - unzip  # [not win]
    
about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html

extra:
  recipe-maintainers:
    - mmcauliffe
    - mcernak
